server.port=8081
spring.application.name=productos

spring.datasource.url=jdbc:mysql://100.30.153.63:3306/beatstoredb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&tcpKeepAlive=true&connectTimeout=8000&socketTimeout=8000&useUnicode=true&characterEncoding=utf8&autoReconnect=true&useIPv4Stack=true
spring.datasource.username=beatstore
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html


